### ISSUE TITLE
Add GeoJSON support to create geometry

### ISSUE THREAD

**Issue by jbelien** [ajthinking/laravel-postgis#2]
Thanks a lot for this library!

It's really convenient to have JSON serialization for all geometry types but I think it would also be really useful to have the inverse functions : being able to create geometries from GeoJSON.

There are already function to create geometries from WKT but not yet (as far as I can tell) from GeoJSON.

Is that something planned or that you would consider ?

**Comment by ajthinking** [comment]
Thanks for your suggestion 👍 That would be a great addition. I have no plans of implementing it personally right now, but will review PRs and would be happy to merge that.

**Comment by jbelien** [comment]
Okay, I'll check if I can easily implement it and submit a PR! 😃
